name: ChestTheft
version: '2.0'
main: com.lonleaf.chesttheft.ChestTheft
api-version: '1.19'
authors: [ lonleaf ]
softdepend: [ MythicMobs, PlaceholderAPI, packetevents, ItemsAdder, MMOItems, Nexo, Oraxen, CraftEngine, NeigeItems, LWC, Bolt, Residence, Dominion, GriefDefender, Towny, WorldGuard, NoBuildPlus]
description: This is a chest theft and lock picking plugin for Minecraft (Spigot).
website: https://github.com/lonlf
commands:
  chesttheft:
    description: ChestTheft main command.
    aliases: [ ct ]
permissions:
  chesttheft.admin:
    default: op
  chesttheft.protectionOwner:
    description: Treat the holder as the owner of any protected chest (overrides owner checks)
    default: op
  chesttheft.check:
    description: View held item information (/ct check)
    default: false
  chesttheft.use:
    description: allow to pickup
    default: true
